version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: impokonrad_db
    environment:
      POSTGRES_USER: impokonrad
      POSTGRES_PASSWORD: impokonrad123
      POSTGRES_DB: impokonrad
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: