"""Add origen_destino_contenedor

Revision ID: 3b30e36bdf47
Revises: ad8b4062253b
Create Date: 2026-04-16 18:55:42.529227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b30e36bdf47'
down_revision: Union[str, None] = 'ad8b4062253b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contenedores', sa.Column('puerto_origen', sa.String(), nullable=True))
    op.add_column('contenedores', sa.Column('puerto_destino', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contenedores', 'puerto_destino')
    op.drop_column('contenedores', 'puerto_origen')
    # ### end Alembic commands ###
