"""Initial migration - create all tables

Revision ID: ad8b4062253b
Revises: 
Create Date: 2026-04-14 20:07:19.724732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8b4062253b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodegas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=False),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('capacidad_actual', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manifiestos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('puerto_origen', sa.String(), nullable=False),
    sa.Column('puerto_destino', sa.String(), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=True),
    sa.Column('fecha_llegada_estimada', sa.DateTime(), nullable=True),
    sa.Column('fecha_llegada_real', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manifiestos_codigo'), 'manifiestos', ['codigo'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'USUARIO', name='rolenum'), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('contenedores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('EN_PUERTO_ORIGEN', 'EN_TRANSITO', 'EN_ADUANA', 'EN_PUERTO_DESTINO', 'ENTREGADO', name='estadocontenedor'), nullable=True),
    sa.Column('bodega_id', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('manifiesto_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['manifiesto_id'], ['manifiestos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contenedores_codigo'), 'contenedores', ['codigo'], unique=True)
    op.create_table('facturas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('numero_factura', sa.String(), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('monto_impuestos', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('archivo_path', sa.String(), nullable=True),
    sa.Column('datos_extraidos_json', sa.Text(), nullable=True),
    sa.Column('procesado_por_ia', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_numero_factura'), 'facturas', ['numero_factura'], unique=False)
    op.create_table('tracking',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contenedor_id', sa.String(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('velocidad', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contenedor_id'], ['contenedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_timestamp'), 'tracking', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_timestamp'), table_name='tracking')
    op.drop_table('tracking')
    op.drop_index(op.f('ix_facturas_numero_factura'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_contenedores_codigo'), table_name='contenedores')
    op.drop_table('contenedores')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_manifiestos_codigo'), table_name='manifiestos')
    op.drop_table('manifiestos')
    op.drop_table('bodegas')
    # ### end Alembic commands ###
